
CREATE TABLE DESCRICAO (
   NSU BIGSERIAL PRIMARY KEY,
   VALOR NUMERIC(15,2),
   DATA_HORA TIMESTAMP,
   ESTABELECIMENTO VARCHAR(255),
   CODIGO_AUTORIZACAO BIGINT UNIQUE,
   STATUS VARCHAR(20)
);

CREATE TABLE TRANSACAO (
   TRANSACAO_ID BIGINT PRIMARY KEY,
   CARTAO VARCHAR(20),

   TIPO_PAGAMENTO VARCHAR(30),
   PARCELAS INTEGER,

   NSU_DESCRICAO BIGINT UNIQUE,

   CONSTRAINT FK_TRANSACAO_DESCRICAO
       FOREIGN KEY (NSU_DESCRICAO)
           REFERENCES DESCRICAO (NSU)
);