spring:
  application:
    name: toolsjavachallenge

  datasource:
    url: jdbc:postgresql://localhost:5432/toolschallenge
    username: postgres
    password: mund0b1t1nf0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true